spring:
  datasource:
    url: ENC(Ob5V/NUuRXUpmOmJfb5+XnPxsop2ijdwVrfXqyjVGW8ZdQPR1c5Wp0bi4nEpCT3m5WAF6cyIn5M+hZiI0tgm2V2fB9E3fBvvKSVvCNqC4jI=)
    driver-class-name: org.mariadb.jdbc.Driver
    username: ENC(vrPD1ktIJWTxgQjBinoH2qzzyDvbnltwga34FyN6yimclYLcDu2GTxcp+8aeDZTp)
    password: ENC(rqKeKpa81pufiw2+HOlpyXA0mgGSNmDOiZHTbTT1Qd8xU9YC6HENn8mQA6C2hI+Y)
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9091